//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthReunionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public int PatientId { get; set; }
        public int ProviderId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public byte[] Document1 { get; set; }
        public string DocumentType { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
