//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthReunionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Documents = new HashSet<Document>();
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int PatientId { get; set; }
        public int ProviderId { get; set; }
        public System.Guid MedicalRecordNumber { get; set; }
        public System.DateTime DOB { get; set; }
        public bool Sex { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public bool IsActive { get; set; }
        public bool RegisteredWithHealthVault { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
