//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthReunionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Documents = new HashSet<Document>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int ProviderId { get; set; }
        public string ProviderName { get; set; }
        public string ProviderDescription { get; set; }
        public string PrivacyStatement { get; set; }
        public string AuthorizationReason { get; set; }
        public string TermsOfUse { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
